In [282]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
from MetodosNumericos import MetodosNumericos

from sklearn.linear_model import LinearRegression
from scipy.stats import linregress
import statsmodels.formula.api as sm

# Practica 

In [283]:
mn = MetodosNumericos()
A_ej = np.array([[7,5,6],[7,2,-1],[5,9,11]])
b_ej = np.array([1,1/2,5])

In [284]:
gauss_result = mn.Gauss(A_ej, b_ej)

In [285]:
gauss_result

[array([[ 7,  5,  6],
        [ 0, -3, -7],
        [ 0,  0, -5]]),
 array([ 1.        , -0.5       ,  3.45238095])]

In [286]:
mn.backward_substi(mn.Doolittle(A_ej)[0], mn.forward_substi(mn.Doolittle(A_ej)[1],b_ej))

/home/juan/miniconda3/envs/st/lib/python3.11/site-packages/scipy/sparse/_index.py:108: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


array([-0.53514739,  1.77777778, -0.69047619])

In [287]:
solu = mn.backward_substi(mn.Gauss(A_ej,b_ej)[0],mn.Gauss(A_ej,b_ej)[1])

In [288]:
solu

array([-0.53514739,  1.77777778, -0.69047619])

In [289]:
print(mn.Doolittle(A_ej)[0])

  (0, 0)	7.0
  (0, 1)	5.0
  (1, 1)	-3.0
  (0, 2)	6.0
  (1, 2)	-7.0
  (2, 2)	-5.0


In [290]:
data = pd.read_csv('data/datos.csv', index_col=0)
data.head()

math  female  socst  read  science
0    41       0     57    57       47
1    53       1     61    68       63
2    54       0     31    44       58
3    47       0     56    63       53
4    57       0     61    47       53

In [291]:
X = data[['math','female','socst','read']]
Y = data.science
lr = LinearRegression()
lr.fit(X,Y)

LinearRegression()

In [292]:
print(f'hat_b0 = {lr.intercept_}')
print(f'hat_b1 = {lr.coef_[0]}')
print(f'hat_b2 = {lr.coef_[1]}')
print(f'hat_b3 = {lr.coef_[2]}')
print(f'hat_b4 = {lr.coef_[3]}')

hat_b0 = 12.325289152291525
hat_b1 = 0.3893101788432859
hat_b2 = -2.0097646543239307
hat_b3 = 0.04984428516656476
hat_b4 = 0.33529979810370303


In [293]:
interc = np.ones([len(data['female']),1])

In [294]:
data['intercepto'] = interc
datos_prueba_X = data.drop('science', axis=1)
A = datos_prueba_X.T.dot(datos_prueba_X)
b = datos_prueba_X.T.dot(data['science'])
A

math  female     socst      read  intercepto
math        571765.0  5711.0  562670.0  562589.0     10529.0
female        5711.0   109.0    5768.0    5639.0       109.0
socst       562670.0  5768.0  572193.0  561036.0     10481.0
read        562589.0  5639.0  561036.0  566514.0     10446.0
intercepto   10529.0   109.0   10481.0   10446.0       200.0

In [295]:
coefs = mn.backward_substi(mn.Gauss(A.to_numpy(),b.to_numpy())[0], mn.Gauss(A.to_numpy(),b.to_numpy())[1])
nombres_variables = datos_prueba_X.columns.tolist()

# Define la cadena de formato
formato = "{:<12} {:>10.4f} "
print("=" * 23) 
print("{:<12} {:>10} ".format("Variable", "Coef"))
print("-" * 23) 

for nombre, coeficiente in zip(nombres_variables, coefs):
    print(formato.format(nombre, coeficiente, 0, 0))

Variable           Coef 
-----------------------
math             0.3893 
female          -2.0098 
socst            0.0498 
read             0.3353 
intercepto      12.3253 


In [297]:
formula = 'science ~ math + female + socst + read'
model = sm.ols(formula = formula, data = data)
fitted = model.fit()
print(fitted.summary())

                            OLS Regression Results                            
Dep. Variable:                science   R-squared:                       0.489
Model:                            OLS   Adj. R-squared:                  0.479
Method:                 Least Squares   F-statistic:                     46.69
Date:                Mon, 08 Apr 2024   Prob (F-statistic):           1.73e-27
Time:                        18:23:50   Log-Likelihood:                -674.63
No. Observations:                 200   AIC:                             1359.
Df Residuals:                     195   BIC:                             1376.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     12.3253      3.194      3.859      0.0

# QR method

In [298]:
A = np.array([[12, -51, 4],
    		[6, 167, -68],
    		[-4, 24, -41]],float)

In [299]:
b = np.array([3, 5, -12],float)

n = A.shape
Q, R = mn.metodoGramm(A,b,n[0])

Al finalizar el algoritmo tendremos:

Matriz Q:
 [[ 0.8571429 -0.3942857 -0.3314286]
 [ 0.4285714  0.9028571  0.0342857]
 [-0.2857143  0.1714286 -0.9428571]]

Matriz R:
 [[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.   0.  35.]]


In [300]:
Qt = np.transpose(Q)

print("\nPara calcular la solucion 'x' del problema, resolveremos R * x = Qt(Q transpuesta) * b",end="\n")

print('\nMatriz Q transpuesta:\n', Qt.round(7))

print('\nVector b:\n', b.round(7))


Para calcular la solucion 'x' del problema, resolveremos R * x = Qt(Q transpuesta) * b

Matriz Q transpuesta:
 [[ 0.8571429  0.4285714 -0.2857143]
 [-0.3942857  0.9028571  0.1714286]
 [-0.3314286  0.0342857 -0.9428571]]

Vector b:
 [  3.   5. -12.]


In [301]:
Qt.dot(b)

array([ 8.14285714,  1.27428571, 10.49142857])